#!/bin/bash -e

me=`basename $0`@`hostname -s`

# Set the script arguments based on the SSH passed args
set -- junk $SSH_ORIGINAL_COMMAND
shift
##DEBUG echo $me $@ '('$# args')'

[ $# -lt 2 ] && echo "$me: Expecting at least two arguments: repo branch(es)" && exit 1
repo=$1
shift
branches=$@
updater=~/$repo

# If an executable file exist at ~/<repo>, run it for each branch with the branch as the argument
if [ -x $updater ]; then
	for branch in $branches
	do
		echo "$me: executing $updater for branch $branch"
		$updater $branch || true
	done
fi

exit 0
